[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.build]
cmds = [
  'cd server',
  'npm ci --only=production'
]

[phases.start]
cmd = 'cd server && node index.js'

[variables]
NODE_ENV = 'production'
PORT = '3001'